### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PIDNet: Unexpected key(s) in state_dict:

### ISSUE THREAD

**Issue by sfatimakhan** [ENOT-AutoDL/lpcv-2023#1]
Traceback (most recent call last):
  File "tools/export_onnx.py", line 56, in <module>
    main()
  File "tools/export_onnx.py", line 28, in main
    model = models.pidnet.get_seg_model(model_name="pidnet_s", num_classes=14, checkpoint_path=args.checkpoint)
  File "/home/lpcv-2023/training/tools/../models/pidnet.py", line 222, in get_seg_model
    model.load_state_dict(new_state_dict, strict=strict_state_dict)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PIDNet:
        Unexpected key(s) in state_dict: "seghead_p.bn1.weight", "seghead_p.bn1.bias", "seghead_p.bn1.running_mean", "seghead_p.bn1.running_var", "seghead_p.bn1.num_batches_tracked", "seghead_p.conv1.weight", "seghead_p.bn2.weight", "seghead_p.bn2.bias", "seghead_p.bn2.running_mean", "seghead_p.bn2.running_var", "seghead_p.bn2.num_batches_tracked", "seghead_p.conv2.weight", "seghead_p.conv2.bias", "seghead_d.bn1.weight", "seghead_d.bn1.bias", "seghead_d.bn1.running_mean", "seghead_d.bn1.running_var", "seghead_d.bn1.num_batches_tracked", "seghead_d.conv1.weight", "seghead_d.bn2.weight", "seghead_d.bn2.bias", "seghead_d.bn2.running_mean", "seghead_d.bn2.running_var", "seghead_d.bn2.num_batches_tracked", "seghead_d.conv2.weight", "seghead_d.conv2.bias".
----------------------------------------------------------------------------------------------------

I am currently done with training and validation. However, I try running the bash script ("bash scripts/export_onnx.sh")  for converting my model to ONNX and come across this issue. Not sure what's wrong!

**Comment by andreysher** [comment]
Hi @sfatimakhan, this issue was fixed in [this](https://github.com/ENOT-AutoDL/lpcv-2023/pull/2) merge.

**Comment by sfatimakhan** [comment]
Hi @andreysher , 
Thanks for resolving the issue. However could you please let me know what was causing the error? I did give a try to resolve but couldn't.
Also, When I tried building my tensorrt engine, I was facing this issue (screen shot attached). I'm using a Jetson Nano 4GB. I got  my ".plan", but I'm not sure if it's correct. The bash script for tensorrt engine gives me a syntax error (fp16:bool syntax issue ), so I ran the python script directly.

<img width="541" alt="Screenshot 2024-02-01 at 1 21 02 PM" src="https://github.com/ENOT-AutoDL/lpcv-2023/assets/125313770/ba43436e-9b79-46f5-9f3a-e94fb30a8cc7">

**Comment by andreysher** [comment]
@sfatimakhan There was unused weights in the state_dict. Those weights are from auxiliary heads, used only during training.

I am not sure that your .plan is correct. I suppose the syntax issue was caused by your python version. We recommend use virtual environment for this project, but according to your screenshot, i suppose the replacement of "python" to "python3" in our .sh scripts will help.

**Comment by sfatimakhan** [comment]
@andreysher 
Thank you so much, will sure give it a try!
