### ISSUE TITLE
TensortRT Engine

### ISSUE THREAD

**Issue by sfatimakhan** [ENOT-AutoDL/lpcv-2023#4]
Hi @andreysher ,
I was attempting on creating the TensorRT engine, and came across this issue (screenshot attached). I haven't made any changes and simply tried running your code. Not sure what's going wrong, Thanks.

Screenshot of where I build the TensorRT Engine 
![Screenshot from 2024-03-27 13-02-33](https://github.com/ENOT-AutoDL/lpcv-2023/assets/125313770/b5e8f718-7596-4ae1-ba3f-45c306a8e3d2)

Screenshot of running the evaluation script
![Screenshot from 2024-03-27 13-02-46](https://github.com/ENOT-AutoDL/lpcv-2023/assets/125313770/a16425af-474d-4f49-ba50-5ffd2012d1cd)

**Comment by AetelFinch** [comment]
Hi @sfatimakhan,
Thank you for your interest! Can you try the following steps to fix the issue?
- move `solution.pyz` to the `lpcv-2023/inference/evaluation` directory;
- in the `evaluation.bash` script change the path in the `path` variable to the absolute path to your `lpcv-2023/inference/evaluation` directory;
- run the `evaluation.bash` script from the `lpcv-2023/inference/evaluation` directory with the command: `./evaluation.bash solution.pyz`.

Also, do not forget to write in the `evaluation.bash` script the path to the test images on which the model will be tested.

**Comment by sfatimakhan** [comment]
Thanks, it worked this time.
